# LINEAR ALGEBRA

In [3]:
import numpy as np

## Scalar, Vector, dan Matrix

In [1]:
# Scalar
S = 5
print(S)

5


In [6]:
# Vector
V = np.array([[1, 2, 3, 4, 5]])
print(V.shape)
print(V)

(1, 5)
[[1 2 3 4 5]]


In [8]:
# Matrix
M = np.matrix([[1, 2, 3], [4, 5, 6], [7,8,9]])
print(M.shape)
print(M)

(3, 3)
[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Operasi-operasi Matrix

In [15]:
# Definisikan Marix A dan B
A = np.matrix([[3, 0],
               [-1,2],
               [1, 1]])

B = np.matrix([[4,-1],
               [0, 2]])

C = np.matrix([[1,4,2],
               [3,1,5]])

print("Ukuran matrix A: ",A.shape)
print("Matrix A: \n", A)
print("\n")
print("Ukuran matrix B: ",B.shape)
print("Matrix B: \n", B)
print("\n")
print("Ukuran matrix C: ",C.shape)
print("Matrix C: \n", C)

Ukuran matrix A:  (3, 2)
Matrix A: 
 [[ 3  0]
 [-1  2]
 [ 1  1]]


Ukuran matrix B:  (2, 2)
Matrix B: 
 [[ 4 -1]
 [ 0  2]]


Ukuran matrix C:  (2, 3)
Matrix C: 
 [[1 4 2]
 [3 1 5]]


**Tentukan (untuk no 1 – 4) matriks hasil operasi berikut ini :**
1. AB
2. 3CA
3. (AB)C
4. (4B)C + 2C

In [16]:
# Soal no 1
A * B

matrix([[12, -3],
        [-4,  5],
        [ 4,  1]])

In [28]:
# Soal no 2
X = 3 * C
print("X = 3 * C:\n", X)
print("\n")
print("X * A: \n", X * A)
print("\n")
print("Atau")
Hasil = 3 * C * A
print("3 x C x A:\n", Hasil)

X = 3 * C:
 [[ 3 12  6]
 [ 9  3 15]]


X * A: 
 [[ 3 30]
 [39 21]]


Atau
3 x C x A:
 [[ 3 30]
 [39 21]]


In [29]:
# Soal no 3
Hasil = (A * B) * C
print("(A x B) x C:\n", Hasil)

(A x B) x C:
 [[  3  45   9]
 [ 11 -11  17]
 [  7  17  13]]


In [32]:
# Soal no 4
Hasil = ((4 * B) * C) + (2 * C)
print("(4 x B) * C + (2 x C):\n", Hasil)

(4 x B) * C + (2 x C):
 [[ 6 68 16]
 [30 10 50]]


## Transpose Matrix

In [34]:
# Transpose Matrix A
print("Matrix A:\n", A)
print("\n")
AT = A.transpose()
print("Transpose Matrix A:\n", AT)

Matrix A:
 [[ 3  0]
 [-1  2]
 [ 1  1]]


Transpose Matrix A:
 [[ 3 -1  1]
 [ 0  2  1]]


In [35]:
# Transpose Matrix B
print("Matrix B:\n", B)
print("\n")
BT = B.transpose()
print("Transpose Matrix B:\n", BT)

Matrix B:
 [[ 4 -1]
 [ 0  2]]


Transpose Matrix B:
 [[ 4  0]
 [-1  2]]


In [36]:
# Transpose Matrix C
print("Matrix C:\n", C)
print("\n")
CT = C.transpose()
print("Transpose Matrix C:\n", CT)

Matrix C:
 [[1 4 2]
 [3 1 5]]


Transpose Matrix C:
 [[1 3]
 [4 1]
 [2 5]]


## Matrix Identitas & Inverse Matrix

In [37]:
# Matrix Identitas
I = np.identity(3)
print("Matrix Identitas:\n", I)

Matrix Identitas:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [39]:
# Inverse Matrix B
# Syarat Inverse: Matrix Harus Memiliki Ordo Sama (Berbentuk persegi) 2x2,3x3,4x4...
print("Matrix B:\n", B)
print("\n")
B_inv = np.linalg.inv(B)
print("Inverse Matrix B:\n", B_inv)

Matrix B:
 [[ 4 -1]
 [ 0  2]]


Inverse Matrix B:
 [[0.25  0.125]
 [0.    0.5  ]]


## Determinan Matrix

In [44]:
# Determinan Matrix B
# Syarat Determinan: Matrix Harus Memiliki Ordo Sama (Berbentuk persegi) 2x2,3x3,4x4...
print("Matrix B:\n", B)
print("\n")
print("Determinan Matrix B:\n", np.linalg.det(B))
det = np.linalg.det(B)
print("Determinan Matrix B (dibulatkan):", round(det))

Matrix B:
 [[ 4 -1]
 [ 0  2]]


Determinan Matrix B:
 7.999999999999998
Determinan Matrix B (dibulatkan): 8


## Solusi Sistem Persamaan Linier

x<sub>1</sub> + x<sub>2</sub> + 2x<sub>2</sub> = 9 <br>
2x<sub>1</sub> + 4x<sub>2</sub> - 3x<sub>3</sub> = 1 <br>
3x<sub>1</sub> + 6x<sub>2</sub> - 5x<sub>3</sub> = 0

In [45]:
a = np.array([[1,1,2], [2,4,-3], [3,6,-5]])
b = np.array([9,1,0])
x = np.linalg.solve(a, b)
x

array([1., 2., 3.])

## Eigen

In [47]:
# Eigen Values
# Syarat Eigen Value: Matrix Harus Memiliki Ordo Sama (Berbentuk persegi) 2x2,3x3,4x4...
print("Matrix B:\n", B)
print("\n")
print("Eigen Values:\n", np.linalg.eigvals(B))

Matrix B:
 [[ 4 -1]
 [ 0  2]]


Eigen Values:
 [4. 2.]


In [ ]:
# Eigen Vector
x = np.array([0,1,0])
a.dot(x) == 2*x